micronaut:
  application:
    name: micronautUsers

datasources:
  default:
    url: jdbc:mysql://db:3306/app?autoReconnect=true&useSSL=false
    username: root
    password: rootpasswd
    driverClassName: com.mysql.cj.jdbc.Driver

jpa.default.properties.hibernate.hbm2ddl.auto: none
